# Spectral Analysis Principles and Tools

add : R code, rjd3toolkit references 

## overview


This scenario is designed for advanced users interested in an in-depth analysis of
time series in the frequency domain using three spectral graphs. Those
graphs can also be used as a complementary analysis for a better
understanding of the results obtained with some of the tests described
above.

Economic time series are usually presented in a time domain (X-axis).
However, for analytical purposes it is convenient to convert the
series to a frequency domain due to the fact that any stationary time
series can be expressed as a combination of cosine (or sine) functions.
These functions are characterized with different periods (amount of time
to complete a full cycle) and amplitudes (maximum/minimum value during
the cycle).

The tool used for the analysis of a time series in a frequency domain is
called a spectrum. The peaks in the spectrum indicate the presence of
cyclical movements with periodicity between two months and one year. A seasonal
series should have peaks at the seasonal
frequencies. Calendar adjusted data are not expected to have peak at with a
calendar frequency.

The periodicity of the phenomenon at frequency *f* is $\frac{2\pi}{f}$. It
means that for a monthly time series the seasonal frequencies
$\frac{\pi}{6},\ \frac{\pi}{3},\ \frac{\pi}{2},\ \frac{2\pi}{3},\ \frac{5\pi}{6}\ $
and $\pi$ correspond to 1, 2, 3, 4, 5 and 6 cycles per year. For
example, the frequency $\frac{\pi}{3}$ corresponds to a periodicity of 6
months (2 cycles per year are completed). For the quarterly series there
are two seasonal frequencies: $\frac{\pi}{2}$ (one cycle per year) and
$\pi$ (two cycles per year). A peak at the zero frequency always
corresponds to the trend component of the series. Seasonal frequencies
are marked as grey vertical lines, while violet vertical lines represent the
trading-days frequencies. The trading day frequency is 0.348 and derives
from the fact that a daily component which repeats every seven days goes
through 4.348 cycles in a month of average length 30.4375 days. It is
therefore seen to advance 0.348 cycles per month when the data are
obtained at twelve equally spaced times in 365.25 days (the average
length of a year).

The interpretation of the spectral graph is rather straightforward. When
the values of a spectral graph for low frequencies (i.e. one year and
more) are large in relation to its other values it means that the
long-term movements dominate in the series. When the values of a
spectral graph for high frequencies (i.e. below one year) are large in
relation to its other values it means that the series are rather
trendless and contains a lot of noise. When the values of a spectral
graph are distributed randomly around a constant without any visible
peaks, then it is highly probable that the series is a random process.
The presence of seasonality in a time series is manifested in a spectral
graph by the peaks on the seasonal frequencies.







